apiVersion: v1
kind: Service
metadata:
  labels:
    service: acc-idnest-redis
  name: acc-idnest-redis
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 6379
    targetPort: 6379
  selector:
    service: acc-idnest-redis
status:
  loadBalancer: {}
