apiVersion: v1
kind: Service
metadata:
  labels:
    service: dead-simple-interface
  name: dead-simple-interface
spec:
  type: NodePort
  ports:
  - name: "80"
    port: 80
  selector:
    service: dead-simple-interface
status:
  loadBalancer: {}
