apiVersion: v1
kind: Service
metadata:
  labels:
    service: qremis-api-redis
  name: qremis-api-redis
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 6379
    targetPort: 6379
  selector:
    service: qremis-api-redis
status:
  loadBalancer: {}
