apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: acc-idnest-redis
  name: acc-idnest-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        service: acc-idnest-redis
    spec:
      containers:
      - command:
        - redis-server
        - --appendonly
        - "yes"
        image: redis
        name: acc-idnest-redis
        resources: {}
      restartPolicy: Always
status: {}
