apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f swarm_stack.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: acc-idnest-redis
  name: acc-idnest-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: acc-idnest-redis
    spec:
      containers:
      - command:
        - redis-server
        - --appendonly
        - "yes"
        image: redis
        name: acc-idnest-redis
        resources: {}
      restartPolicy: Always
status: {}
