apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f swarm_stack.yml
    kompose.version: 1.2.0 (99f88ef)
  creationTimestamp: null
  labels:
    io.kompose.service: ingress
  name: ingress
spec:
  type: NodePort
  port: 80
  selector:
    io.kompose.service: unifier
status:
  loadBalancer: {}
