apiVersion: v1
kind: Service
metadata:
  labels:
    service: rec-mongo
  name: rec-mongo
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 27017
    targetPort: 27017
  selector:
    service: rec-mongo
status:
  loadBalancer: {}
