apiVersion: v1
kind: Service
metadata:
  labels:
    service: rec-api
  name: rec-api
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 80
    targetPort: 80
  selector:
    service: rec-api
status:
  loadBalancer: {}
